version: 2

defaults: &defaults
    working_directory: ~/repo
    docker:
        - image: cypress/base:10
    environment:
        # Enable colors in the output
        TERM: xterm

jobs:
    test:
        <<: *defaults
        steps:
            - checkout
            - restore_cache:
                keys:
                - v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
                - v1-deps-{{ .Branch }}
                - v1-deps

            - run: npm ci
            - run: npx tsc
            - run:
                name: Run tests
                command: npx cypress run
                environment:
                    CYPRESS_CRASH_REPORTS: 0

            - save_cache:
                paths:
                    - node_modules
                key: v1-deps-{{ .Branch }}-{{ checksum "package.json" }}

            - persist_to_workspace:
                root: ~/repo
                paths: .

    deploy:
        <<: *defaults
        steps:
            - attach_workspace:
                at: ~/repo
            - run:
                name: Publish package
                command: |
                    npm set //registry.npmjs.org/:_authToken=$NPM_TOKEN
                    npm publish

workflows:
    version: 2
    test-deploy:
        jobs:
            - test:
                filters:
                    tags:
                        only: /^v[0-9]+(\.[0-9]+).*/

            - deploy:
                requires:
                    - test
                filters:
                    tags:
                        only: /^v[0-9]+(\.[0-9]+).*/

