version: 2.1

executors:
    cypress-base-10:
        docker:
            - image: cypress/base:10
        working_directory: ~/repo

references:
    filter_version_tag: &filter_version_tag
        tags:
            only:
                - /^v\d+(\.\d+).*/
        branches:
            ignore: /.*/

jobs:
    test:
        executor: cypress-base-10
        steps:
            - checkout
            - restore_cache:
                keys:
                    - v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
                    - v1-deps-{{ .Branch }}
                    - v1-deps
            - run: npm ci
            - run: npx tsc
            - run:
                name: Run tests
                command: npx cypress run
                environment:
                    CYPRESS_CRASH_REPORTS: 0

            - save_cache:
                paths:
                    - node_modules
                key: v1-deps-{{ .Branch }}-{{ checksum "package.json" }}

            - persist_to_workspace:
                root: ~/repo
                paths: .

    publish:
        executor: cypress-base-10
        steps:
            - attach_workspace:
                at: ~/repo
            - run:
                name: Publish to npm
                command: |
                    npm set //registry.npmjs.org/:_authToken=$NPM_TOKEN
                    npm publish

workflows:
    version: 2

    build-test:
        jobs:
            - test

    build-test-publish:
        jobs:
            - test:
                filters:
                    <<: *filter_version_tag
            - publish:
                requires:
                    - test
                filters:
                    <<: *filter_version_tag

